### PR TITLE
feat: 🎸 ESM Loading. Remove System JS. IE Support. CSS Hydration Fixes. Naming Conflict fixes. Robust support for plugins. 

### LINKED ISSUE #66: CSS Sourcemap
How would I get CSS sourcemaps to work with DevTools > Sources > Filesystem? I don't really know Rollup options as you can probably tell, but as I understand there's the Replacements section in the docs which serves this purpose. What isn't clear to me is if it's just a placeholder name or if that's exactly what you need to type in to change the Rollup config. There's no mention of how to get this specific feature working, or if it's even remotely possible.

I tried adding `sourceMap: true` to `svelte.config.js` but maybe that's completely unrelated.

Also, I'm wondering if anyone even uses sourcemaps since I've only seen brief mention of it in documentation on Rollup.

### PR DESCRIPTION
**Pull request by nickreese**
This add the ability to split components to dev which will speed up local dev but breaks stores.

### Usage:

```
module.exports = [...getRollupConfig({ svelteConfig, 
rollupConfig: { 
dev: { splitComponents: true } 
} 
})];
```

Also got a working module/nomodule setup built using `iife`s that doesn't break the Elder.js apis.

### Testing
To test this:
1. clone this branch and type `npm install && npm link`
1. degit the template with `npx degit Elderjs/template elderjs-app`
1. `cd elderjs-app`
1. Update the `@elderjs/elderjs` entry in the `package.json` to be `file:../relative/path/here/` and then type `npm install`.
1. `npm run build`

### Notes:
* This also completely refactors how we're getting CSS, adds CSS sourcemaps, and fixes #66, #34, #37 and #34.
* This also fixes naming conflicts #41. 
* It adds more robust support for plugin templates.

### CODE REVIEW

**Comment by jbmoelker** [comment]
Very curious about this feature. Just putting some findings here first, without having looked at the code:

* Test step 4, you can use a linked package using `npm link @elderjs/elderjs` inside `elderjs-app/`.
* `npm run rollup:dev` no longer works without `rollupConfig: { dev: { splitComponents: true } }`. Can that become optional?
* Maybe it's odd to have a `rollupConfig` property in `getRollupConfig`? Could this be `getRollupConfig({ dev: { ... }, svelteConfig })`?
* When I run `dev:rollup` and `dev:server` and I open `http://localhost:3000/` I get a 404 on `http://localhost:3000/svelte/undefined.mjs` and the clock doesn't hydrate. Is it supposed to do that? If I set `{ splitComponents: false }` it loads and hydrates again. Without SystemJS, so 🥳.

When I run a `build` and serve it locally using `npx serve public/`, the page works both in modern browsers and IE11. 💯

So quick first verdict would be that this should make it in :) Maybe without the `dev: { splitComponents: true }` to start with?

File: src/utils/getHashedSvelteComponents.ts [hunk 1]
```diff
@@ -15,19 +15,31 @@ const getHashedSvelteComponents = ({ ssrComponents, clientComponents }) => {
...
     // CityResults.js => CityResults
     const ssr = ssrFiles.map((s) => s.split('/').pop().split('.')[0]);
 
-    const client = clientFiles.map((s) => s.split('/').pop().split('.')[0]);
+    const jsClient = jsClientFiles.map((s) => s.split('/').pop().split('.')[0]);
+    const mjsClient = mjsClientFiles.map((s) => s.split('/').pop().split('.')[0]);
 
     // match the SSR version (no hash) to a hashed version.
     // allowing the correct file name to be looked up by the SSR key.
     results = ssr.reduce((out, cv) => {
```
Comment (jbmoelker) [inline src/utils/getHashedSvelteComponents.ts:30]: I think this could be simplified a bit, but I'm not sure how :) What is the desired output?

File: src/utils/svelteComponent.ts [hunk 2]
```diff
@@ -41,11 +41,14 @@ const svelteComponent = (componentName) => ({ page, props, hydrateOptions }: Com
     const { render } = require(ssrComponent);
     componentCache[cleanComponentName] = {
       render,
-      clientSrc: `${clientSvelteFolder}/${clientComponents[cleanComponentName]}.js`,
+      clientSrcSystem: `${clientSvelteFolder}/${clientComponents[cleanComponentName].system}.js`,
```
Comment (jbmoelker) [inline src/utils/svelteComponent.ts:44]: Maybe make the naming here a bit more consist, so that you can use the same logic? Something like:

```js
// this can probably be reused in different places
const fileTypes = [
  { type: 'system', ext: 'js' },
  { type: 'mjs', ext: 'mjs' },
  { type: 'iife', ext: 'js' },
  { type: 'nomodule', ext: 'js' },
];

componentCache[cleanComponentName] = {
  render,
  filename: fileTypes.reduce((out, { type, ext}) => {
    ...out,
    [type]: path.join(clientSvelteFolder, `${clientComponents[cleanComponentName][type]}.${ext}`)
  }, {}),
};
```

**Review by jbmoelker — COMMENTED** [review]
Complex stuff. Great that you're digging into this. I can't think of a simpler solution. So for now, just left some small comments.

I do really enjoy seeing the module/nomodule script mechanism at work. As I think it's a really lean solution for wide browser support.

File: src/utils/getHashedSvelteComponents.ts (hunk 1 above)
Comment (nickreese) [reply src/utils/getHashedSvelteComponents.ts:30]: lol, yep. trying to get the basename. your function above is great.

File: src/utils/getHashedSvelteComponents.ts [hunk 3]
```diff
@@ -15,19 +15,31 @@ const getHashedSvelteComponents = ({ ssrComponents, clientComponents }) => {
     ready = true;
 
     const ssrFiles = glob.sync(`${ssrComponents}/*.js`, {});
-    const clientFiles = glob.sync(`${clientComponents}/*.js`, {});
+    const jsClientFiles = glob.sync(`${clientComponents}/*.js`, {});
```
[the remark this answers is not in the document]
Comment (nickreese) [reply src/utils/getHashedSvelteComponents.ts:18]: Good tip. Didn't use it here but will use it in the future.

**Comment by nickreese** [comment]
@halafi @jbmoelker @decrek I think this is ready to merge in and release. 👍 

Filip, we could use some tests for some of the new features/improvements when you have downtime.

**Comment by nickreese** [comment]
Just a note that we're still hacking on this.

**Comment by nickreese** [comment]
Still having an issue on ElderGuide (beyond css) 

image

**Comment by decrek** [comment]
@nickreese The repo for Elder Guide is not open right? If you want I can have a glance at the code Elder Guide code, maybe I can help identify if the error is Elder Guide specific or actually comes from Elder itself.

**Comment by nickreese** [comment]
@thisislawatts Here is a monster PR with a ton of changes. Would love more eyes on this if you're curious. 👍

**Comment by nickreese** [comment]
It appears some of my changes to the babel config broke ie11. Tomorrow is another day lol.

File: src/utils/__tests__/rollupPluginHandleCss.spec.ts [hunk 4]
```diff
@@ -0,0 +1,152 @@
...
+  map: undefined,
+  referencedFiles: [],
+};
+
+beforeEach(() => {
+  jest.resetModules();
+});
+
+describe('#rollupPluginHandleCss', () => {
+  const { name } = rollupPluginHandleCss({ rootDir: 'test' });
```
Comment (halafi) [inline src/utils/__tests__/rollupPluginHandleCss.spec.ts:84]: maybe it should go to 'name' test, as the error can be scoped to that test failure

**Comment by thisislawatts** [comment]
@nickreese this PR is a little hard for me to review given it's size. Have you considered rebasing against `master` branch to reduce some of noise here. Are there any specific changes you would like extra eyes on?

**Comment by nickreese** [comment]
@thisislawatts I’ll need to google rebase. 👀 

This started as a refactor for ESM/ie11 bundles which deeply changed our rollup configs. Then I wanted to fix the CSS issues as it was closely changed with the rollup configs. The problem was that the string kept going as the only way to pull off the CSS implementation was to make sure there weren’t component name shadowing and even a deeper refactor of the rollup configs.  

I’ll look at rebase. This is tested against the template and 2 production projects so I’m confident in the fact the code works. Just mainly realize that more eyes are better than fewer but overall I think it is ready to merge.
